### ISSUE TITLE
For gRNA design, inputting a value for flanking causes the software to run forever

### ISSUE THREAD

**Issue by AlexBorengasser** [pritykinlab/guidescanpy#7]
E.g., if I set Flanking to 100, the gRNA output is never shown (I've kept the page open for about 25 minutes, and nothing comes up).

**Comment by vineetbansal** [comment]
@AlexBorengasser . There were 2 issues going on there:
- If a job fails (for whatever reason - a bad input or a bug in the server code), that screen would sit there forever and not show you that something went wrong. This is fixed now, so that if there is a bug, you will see an error screen.
- The actual bug itself has been fixed (hopefully), so you should see results for flanking in the resulting screen.

Give it a try and see if it's working better now.

**Comment by vineetbansal** [comment]
Issue #6 should also be fixed (where only results for the last gene/coordinate were shown), so give that another go as well..

**Comment by vineetbansal** [comment]
This is fixed, so closing the issue. Feel free to open if we missed something.
